# Generated by Django 4.0.5 on 2022-07-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-created'], 'verbose_name': 'portfolio', 'verbose_name_plural': 'portfolios'},
        ),
        migrations.AlterField(
            model_name='work',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(upload_to='portfolios', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='work',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion'),
        ),
    ]
